kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
kff_version=4.11.0

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=experienced_equipment
mod_name=Experienced Equipment
mod_version=1.0.0
mod_authors=TheEnderCore
mod_description=A mod to lock armor behind a level requirement.
mod_license=MIT
mod_group_id=com.theendercore.experienced_equipment
